# Generated by Django 2.2 on 2019-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizname', models.CharField(max_length=250)),
                ('quizId', models.CharField(max_length=250)),
                ('quizProgrammingLanguage', models.CharField(max_length=250)),
                ('quizSkill', models.CharField(max_length=250)),
            ],
        ),
    ]
